% script for fixing up indivudal eeg files that didn't work

EEG1 = pop_select(EEG, 'time', [0, 900]);

Filename = EEG.filename;
Destination = 'D:\LSM\data\P06\LAT\BaselineBeam\EEG';
 pop_saveset(EEG1, 'filename', Filename, ...
            'filepath', Destination, ...
            'check', 'on', ...
            'savemode', 'onefile', ...
            'version', '7.3');